/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


var mongoose = require('mongoose');

var courseSchema = mongoose.Schema({
    title: {type: String, required: '{PATH} is required!'},
    featured: {type: Boolean, required: '{PATH} is required!'},
    
    published: {type: Date, required: '{PATH} is required!'},
    //tags: {type: [String], required: '{PATH} is required!'}
    content: {type: String}, 
    tags:[String]
});

var Course = mongoose.model('Course', courseSchema);

function createDefaultCourses(){
    Course.find({}).exec(function(err, collection){
        if(collection.length === 0){
            Course.create({title: 'Machine learning', featured: true, published: new Date('10/5/2016'), tags:['CS'], content:'Machine learning is the science of getting computers to act without being explicitly programmed. In the past decade, machine learning has given us self-driving cars, practical speech recognition, effective web search, and a vastly improved understanding of the human genome. Machine learning is so pervasive today that you probably use it dozens of times a day without knowing it. Many researchers also think it is the best way to make progress towards human-level AI. In this class, you will learn about the most effective machine learning techniques, and gain practice implementing them and getting them to work for yourself. More importantly, you will learn about not only the theoretical underpinnings of learning, but also gain the practical know-how needed to quickly and powerfully apply these techniques to new problems. Finally, you will learn about some of Silicon Valley best practices in innovation as it pertains to machine learning and AI.'});
            Course.create({title: 'Regression Models', featured: true, published: new Date('10/12/2016'), tags:['CS'], content:'Linear models, as their name implies, relates an outcome to a set of predictors of interest using linear assumptions.  Regression models, a subset of linear models, are the most important statistical analysis tool in a data scientist’s toolkit. This course covers regression analysis, least squares and inference using regression models. Special cases of the regression model, ANOVA and ANCOVA will be covered as well. Analysis of residuals and variability will be investigated. The course will cover modern thinking on model selection and novel uses of regression models including scatterplot smoothing.'});
            Course.create({title: 'Python Data Structures', featured: false, published: new Date('10/1/2016'), tags:['CS'], content:'This course will introduce the core data structures of the Python programming language. We will move past the basics of procedural programming and explore how we can use the Python built-in data structures such as lists, dictionaries, and tuples to perform increasingly complex data analysis. This course will cover Chapters 6-10 of the textbook “Python for Informatics”.  This course is equivalent to the second half of the 11-week "Programming for Everybody (Python)" course.'});
            Course.create({title: 'Algorithms: Design and Analysis', featured: false, published: new Date('7/12/2016'), tags:['CS'], content:'Algorithms are the heart of computer science, and the subject has countless practical applications as well as intellectual depth.  This course is an introduction to algorithms for learners with at least a little programming experience.  The course is rigorous but emphasizes the big picture and conceptual understanding over low-level implementation and mathematical details.  After completing this course, you will be well-positioned to ace your technical interviews and speak fluently about algorithms with other programmers and computer scientists.'});
            Course.create({title: 'Ruby on Rails Web Development Specialization', featured: true, published: new Date('1/1/2016'), tags:['CS'], content:'This Specialization covers the fundamentals of web development with Ruby on Rails. You’ll learn everything you need to develop your own web application using Ruby on Rails, SQL and NoSQL databases, and HTML/CSS, and Javascript. We will also touch on advanced topics such as security, services using HTTP/RESTful access patterns, and user access and user experience from multiple device platforms. In the final Capstone Project, you’ll apply your skills to develop a web application that hosts uploaded photos and displays them using a map.'});
            Course.create({title: 'Functional Program Design in Scala', featured: true, published: new Date('10/13/2016'), tags:['CS'], content:'In this course you will learn how to apply the functional programming style in the design of larger applications. You will get to know important new functional programming concepts, from lazy evaluation to structuring your libraries using monads. We will work on larger and more involved examples, from state space exploration to random testing to discrete circuit simulators. You’ll also learn some best practices on how to write good Scala code in the real world.'});
            Course.create({title: 'Front-End Web UI Frameworks', featured: true, published: new Date('3/1/2016'), tags:['CS'], content:'This course will give you an overview of client-side web frameworks, in particular Bootstrap. You will learn about grids and responsive design, Bootstrap CSS and JavaScript components. You will learn about CSS preprocessors, Less and Sass. You will also learn the basics of Node.js and NPM and learn about Web tools like Bower.'});
            Course.create({title: 'Successful Negotiation', featured: true, published: new Date('2/1/2016'), tags:['Business'], content:'Through this course you will learn and practice the strategies and skills that will help you become a successful negotiator in your personal life and business transactions. After completing this module, you will be able to state the four key stages of negotiation and what you need to do successfully complete this course. '});
            Course.create({title: 'Financial Markets', featured: true, published: new Date('10/7/2016'), tags:['Business'], content:'This course will introduce portfolio diversification, supporting financial institutions, and discusse the opportunities and vulnerabilities of risk management institutions.'});
            Course.create({title: 'Introduction to Financial Accounting', featured: false, published: new Date('8/1/2016'), tags:['Business'], content:'Master the technical skills needed to analyze financial statements and disclosures for use in financial analysis, and learn how accounting standards and managerial incentives affect the financial reporting process. By the end of this course, you’ll be able to read the three most common financial statements: the income statement, balance sheet, and statement of cash flows. Then you can apply these skills to a real-world business challenge as part of the Wharton Business Foundations Specialization.'});
            Course.create({title: 'Design Thinking for Innovation', featured: false, published: new Date('11/1/2016'), tags:['Business'], content:'In this course, we provide an overview of design thinking and work with a model containing four key questions and several tools to help you understand design thinking as a problem solving approach. We also look at several stories from different organizations that used design thinking to uncover compelling solutions.'});
            Course.create({title: 'Project Management: The Basics for Success', featured: true, published: new Date('10/13/2016'), tags:['Business'], content:'This course combines the essential elements of Project Management and Team Leadership into one course. Through class engagement and reflection, you will acquire further understanding of the responsibilities of leadership and become better prepared to apply this knowledge to the project environment.'});
            Course.create({title: 'High-Impact Business Writing', featured: true, published: new Date('10/1/2016'), tags:['Business'], content:'Effective writing is a powerful tool in the business environment. Learn how to articulate your thoughts in a clear and concise manner that will allow your ideas to be better understood by your readers. Improve your business writing skill by learning to select and use appropriate formats for your audience, use the correct medium and adjust your writing style accordingly, as well as identify your objective and communicate it clearly. You will also learn to spot, correct and avoid the most common writing pitfalls, and gain valuable experience analyzing, writing and revising a wide spectrum of business documents. From a simple interoffice memo to a twenty-page business proposal, learn how to put good business writing to work for you'});
            Course.create({title: 'Strategy Formulation', featured: false, published: new Date('2/15/2016'), tags:['Business'], content:'The purpose of this course is to present, analyze and discuss the different facets of business strategy formulation. Emphasizing that strategy can be seen as a unified theme that provides coherence and direction to the actions and decisions of a firm, we will cover a variety of business strategy topics concerned with firm positioning in the context of different markets, industries and locations.'});
            Course.create({title: 'Increasing Real Estate Management Profits: Harnessing Data Analytics', featured: true, published: new Date('7/1/2016'), tags:['social'], content:'In this final course you will complete a Capstone Project using data analysis to recommend a method for improving profits for your company, Watershed Property Management, Inc. Watershed is responsible for managing thousands of residential rental properties throughout the United States. Your job is to persuade Watershed’s management team to pursue a new strategy for managing its properties that will increase their profits. To do this, you will: (1) Elicit information about important variables relevant to your analysis; (2) Draw upon your new MySQL database skills to extract relevant data from a real estate database; (3) Implement data analysis in Excel to identify the best opportunities for Watershed to increase revenue and maximize profits, while managing any new risks; (4) Create a Tableau dashboard to show Watershed executives the results of a sensitivity analysis; and (5) Articulate a significant and innovative business process change for Watershed based on your data analysis, that you will recommend to company executives. '});
        }
    })
}

exports.createDefaultCourses = createDefaultCourses; 
  
